//暂时这里更改无效，直接更改audio_nvram_def.c
/*
    {
        NVRAM_EF_SYS_ABNORMAL_LID,
        NVRAM_EF_SYS_ABNORMAL_TOTAL,
        NVRAM_EF_SYS_ABNORMAL_SIZE,
        NVRAM_NORMAL(NVRAM_EF_ZERO_DEFAULT),
        NVRAM_CATEGORY_USER,
        NVRAM_ATTR_AVERAGE | NVRAM_ATTR_FACTORY_RESET,
        "MPE9",
        VER(NVRAM_EF_SYS_ABNORMAL_LID)
    },
    {
        NVRAM_EF_GPS_POSITION_LID,
        NVRAM_EF_GPS_POSITION_TOTAL,
        NVRAM_EF_GPS_POSITION_SIZE,
        NVRAM_NORMAL(NVRAM_EF_ZERO_DEFAULT),
        NVRAM_CATEGORY_USER,
        NVRAM_ATTR_AVERAGE | NVRAM_ATTR_FACTORY_RESET,
        "MPEE",
        VER(NVRAM_EF_GPS_POSITION_LID)
    },
    {
        NVRAM_EF_GPS_BACKUP_DATA_PARAM_LID,
        NVRAM_EF_GPS_BACKUP_DATA_PARAM_TOTAL,
        NVRAM_EF_GPS_BACKUP_DATA_PARAM_SIZE,
        NVRAM_NORMAL((const kal_uint8 *)NVRAM_EF_GPS_BACKUP_DATA_PARAM_DEFAULT),
        NVRAM_CATEGORY_USER ,
        NVRAM_ATTR_AVERAGE | NVRAM_ATTR_FACTORY_RESET,
        "MPEG",
        VER(NVRAM_EF_GPS_BACKUP_DATA_PARAM_LID)
    },

    {
        NVRAM_EF_CHECK_OTA_LID,
        NVRAM_EF_CHECK_OTA_TOTAL,
        NVRAM_EF_CHECK_OTA_SIZE,
        NVRAM_NORMAL((const kal_uint8 *)NVRAM_EF_CHECK_OTA_DEFAULT),
        NVRAM_CATEGORY_USER,
        NVRAM_ATTR_AVERAGE | NVRAM_ATTR_FACTORY_RESET,
        "OTA01",
        VER(NVRAM_EF_CHECK_OTA_LID)
    },
*/

